version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=Ahmmed_1211
      - MYSQL_PASSWORD=Ahmmed_1211 # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  www:
    build: .
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80